name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - ./*.md
      - ./*.txt
      - .gitignore

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-XX:MaxMetaspaceSize=2g"
  JDK_VERSION: 19

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ env.JDK_VERSION }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JDK_VERSION }}
          distribution: "temurin"
          server-id: github
          settings-path: ${{ github.workspace }}
          cache: "gradle"

      - name: ./gradlew permissions
        run: chmod +x ./gradlew

      - name: Prepare libraries configs
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          MAPBOX_API_CREDS: ${{ secrets.MAPBOX_API_CREDS }}
        run: |
          echo $GOOGLE_SERVICES_JSON > ./app/google-services.json
          echo $MAPBOX_API_CREDS >> ~/.gradle/gradle.properties

      - name: Test with JDK ${{ env.JDK_VERSION }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            test

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          trunk-token: ${{ secrets.TRUNK_TOKEN }}

      - name: Build with analyze
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Gradle dependency submission
        uses: mikepenz/gradle-dependency-submission@v0.8.6
        with:
          gradle-build-module: :app

      - name: Qodana scan
        uses: JetBrains/qodana-action@main
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
