name: ci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**.txt"
      - "**.json"
      - ".gitignore"
    tags-ignore:
      - "*"

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-XX:MaxMetaspaceSize=2g"
  JDK_VERSION: 8

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ env.JDK_VERSION }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JDK_VERSION }}
          distribution: "temurin"
          server-id: github
          settings-path: ${{ github.workspace }}
          cache: 'gradle'

      - name: ./gradlew permissions
        run: chmod +x ./gradlew

      - name: Test with JDK ${{ env.JDK_VERSION }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

      - name: Build with analyze
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@main
        with:
          sarif_file: build/reports/detekt/merge.sarif

      - name: Gradle dependency submission
        uses: mikepenz/gradle-dependency-submission@v0.8.6
        with:
          gradle-build-module: :app
