name: ci

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**.txt"
      - "**.json"
      - ".gitignore"
    tags-ignore:
      - "*"

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-XX:MaxMetaspaceSize=2g"
  JDK_VERSION: 19

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ env.JDK_VERSION }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JDK_VERSION }}
          distribution: "temurin"
          server-id: github
          settings-path: ${{ github.workspace }}
          cache: "gradle"

      - name: ./gradlew permissions
        run: chmod +x ./gradlew

      - name: Test with JDK ${{ env.JDK_VERSION }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            test
            -PmapboxUsername=mapbox
            -PmapboxPassword=${{ secrets.MAPBOX_TOKEN }}

      - name: Build with analyze
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            build
            -PmapboxUsername=mapbox
            -PmapboxPassword=${{ secrets.MAPBOX_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Gradle dependency submission
        uses: mikepenz/gradle-dependency-submission@v0.8.6
        with:
          gradle-build-module: :app

      - name: Qodana scan
        uses: JetBrains/qodana-action@main
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
