name: trunk
on:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:

permissions: read-all

jobs:
  upgrade:
    name: upgrade trunk
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Trunk Upgrade
        uses: trunk-io/trunk-action/upgrade@v1
