name: trunk
on:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:

permissions: read-all

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-XX:MaxMetaspaceSize=2g"
  JDK_VERSION: 19

jobs:
  upgrade:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ env.JDK_VERSION }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JDK_VERSION }}
          distribution: "temurin"
          server-id: github
          settings-path: ${{ github.workspace }}
          cache: "gradle"

      - name: ./gradlew permissions
        run: chmod +x ./gradlew

      - name: Prepare libraries configs
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          MAPBOX_API_CREDS: ${{ secrets.MAPBOX_API_CREDS }}
          MAPBOX_PUBLIC_KEY: ${{ secrets.MAPBOX_PUBLIC_KEY }}
        run: |
          echo $GOOGLE_SERVICES_JSON > ./app/google-services.json
          mkdir -p ~/.gradle
          echo $MAPBOX_API_CREDS > ~/.gradle/gradle.properties
          echo $MAPBOX_PUBLIC_KEY > ./app/src/main/res/values/dev.xml

      - name: Gradle checks
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check

      - name: Trunk Upgrade
        uses: trunk-io/trunk-action/upgrade@v1
