name: trunk

on:
  workflow_run:
    workflows: ["Pull Request"]
    types: [completed]

jobs:
  check:
    name: Annotated trunk checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          post-annotations: true
